### Delete index
### delete all categories
POST http://localhost:9200/categories/_delete_by_query
Content-Type: application/json

{
    "query": {
        "match_all": {}
    }
}

### search categories
POST http://localhost:9200/categories/_search
Content-Type: application/json


### close index categories
POST http://localhost:9200/categories/_close

### restore categories from snapshot
POST http://localhost:9200/_snapshot/first_backup/snapshot1/_restore
Content-Type: application/json

{
    "indices": [
        "categories"
    ]
}


### open index categories
POST http://localhost:9200/categories/_open


### search categories
POST http://localhost:9200/categories/_search

### check index
GET http://localhost:9200/_cat/indices?v