### Create snapshot repository
### Location is path.repo/location
PUT http://localhost:9200/_snapshot/first_backup
Content-Type: application/json

{    
    "type": "fs",
    "settings": {
        "location": "first_backup"
    }
}

### Get repo
GET http://localhost:9200/_snapshot

### Create snapshot
PUT http://localhost:9200/_snapshot/first_backup/snapshot1
Content-Type: application/json

{
    "indices": [],
    "metadata": {
        "taken_by": "dicky",
        "taken_because": "backup before upgrading"
    }
}

### get snapshot
GET http://localhost:9200/_snapshot/first_backup/snapshot1
### list snapshots
GET http://localhost:9200/_cat/snapshots?v